# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.237"
    hooks:
      - id: ruff
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
